name: Release Management

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'package.json'

jobs:
  version-and-release:
    if: '!contains(github.event.head_commit.message, ''chore: bump version'')'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Update Version
        id: version
        run: |
          # package.json에서 현재 버전 가져오기
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "Current version: $CURRENT_VERSION"
          
          # 커밋 메시지에서 major 또는 minor 업데이트 확인
          COMMIT_MSG=$(git log -1 --pretty=%B)
          if [[ $COMMIT_MSG == *"#major"* ]]; then
            # major 버전 업데이트 (x.0.1)
            NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. '{print ($1+1) ".0.1"}')
          elif [[ $COMMIT_MSG == *"#minor"* ]]; then
            # minor 버전 업데이트 (x.x.1)
            NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. '{print $1 "." ($2+1) ".1"}')
          else
            # patch 버전 업데이트 (x.x.x+1)
            NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. '{print $1 "." $2 "." ($3+1)}')
          fi
          
          echo "New version: $NEW_VERSION"
          
          # package.json 업데이트
          npm version $NEW_VERSION --no-git-tag-version
          
          # 변수 저장
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add package.json
          git commit -m "chore: bump version to ${{ steps.version.outputs.new_version }}"
          git tag "v${{ steps.version.outputs.new_version }}"
          git push
          git push --tags

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ steps.version.outputs.new_version }}"
          name: "Release v${{ steps.version.outputs.new_version }}"
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }} 